### ISSUE TITLE
求问网盘上的模型是 Part_A的吗?

### ISSUE THREAD

**Issue by Amelie01** [CommissarMa/Context-Aware_Crowd_Counting-pytorch#17]
"MAE at the 353 epoch BaiduDisk download with Extraction code: yfwb". 求问这个模型是part_A的吗? 我直接用这个测试part_A, 得到 mae:413.119863447

**Comment by CommissarMa** [comment]
是partA的



---原始邮件---
发件人: "Amelie"<notifications@github.com&gt;
发送时间: 2019年8月27日(星期二) 晚上10:00
收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17)



"MAE at the 353 epoch BaiduDisk download with Extraction code: yfwb". 求问这个模型是part_A的吗? 我直接用这个测试part_A, 得到 mae:413.119863447

**Comment by Amelie01** [comment]
> 是partA的
> […](#)
> ---原始邮件--- 发件人: "Amelie"<notifications@github.com&gt; 发送时间: 2019年8月27日(星期二) 晚上10:00 收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17) "MAE at the 353 epoch BaiduDisk download with Extraction code: yfwb". 求问这个模型是part_A的吗? 我直接用这个测试part_A, 得到 mae:413.119863447 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Amelie01** [comment]
我直接用给的代码生成了test数据集,然后load 模型测试, pytorch 0.4.1, python 2.7,结果出入还是蛮大,后脸皮求问,可能是什么问题?

**Comment by Amelie01** [comment]
我直接用给的代码生成了test数据集,然后load 模型测试, pytorch 0.4.1, python 2.7,结果出入还是蛮大,后脸皮求问,可能是什么问题?

> 是partA的
> […](#)
> ---原始邮件--- 发件人: "Amelie"<notifications@github.com&gt; 发送时间: 2019年8月27日(星期二) 晚上10:00 收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17) "MAE at the 353 epoch BaiduDisk download with Extraction code: yfwb". 求问这个模型是part_A的吗? 我直接用这个测试part_A, 得到 mae:413.119863447 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CommissarMa** [comment]
把预测的密度图可视化出来，看看是不是和ground truth相似。



---原始邮件---
发件人: "Amelie"<notifications@github.com&gt;
发送时间: 2019年8月27日(星期二) 晚上10:25
收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Ma Zhenwei"<960901625@qq.com&gt;;
主题: Re: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17)



我直接用给的代码生成了test数据集,然后load 模型测试, pytorch 0.4.1, python 2.7,结果出入还是蛮大,后脸皮求问,可能是什么问题?
  
是partA的
 …
 ---原始邮件--- 发件人: "Amelie"<notifications@github.com&gt; 发送时间: 2019年8月27日(星期二) 晚上10:00 收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17) "MAE at the 353 epoch BaiduDisk download with Extraction code: yfwb". 求问这个模型是part_A的吗? 我直接用这个测试part_A, 得到 mae:413.119863447 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Amelie01** [comment]
> 把预测的密度图可视化出来，看看是不是和ground truth相似。
> […](#)
> ---原始邮件--- 发件人: "Amelie"<notifications@github.com&gt; 发送时间: 2019年8月27日(星期二) 晚上10:25 收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Ma Zhenwei"<960901625@qq.com&gt;; 主题: Re: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17) 我直接用给的代码生成了test数据集,然后load 模型测试, pytorch 0.4.1, python 2.7,结果出入还是蛮大,后脸皮求问,可能是什么问题? 是partA的 … ---原始邮件--- 发件人: "Amelie"<notifications@github.com&gt; 发送时间: 2019年8月27日(星期二) 晚上10:00 收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17) "MAE at the 353 epoch BaiduDisk download with Extraction code: yfwb". 求问这个模型是part_A的吗? 我直接用这个测试part_A, 得到 mae:413.119863447 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好的我去试试多谢!

**Comment by xixiareone** [comment]
可以分享一下UCF-QNRF和UCF-50的pretrained model吗？非常感谢！

**Comment by CommissarMa** [comment]
我没训练这两个数据集，最近在写新论文，sorry



---原始邮件---
发件人: "xixiareone"<notifications@github.com&gt;
发送时间: 2019年9月3日(星期二) 上午8:29
收件人: "CommissarMa/Context-Aware_Crowd_Counting-pytorch"<Context-Aware_Crowd_Counting-pytorch@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Ma Zhenwei"<960901625@qq.com&gt;;
主题: Re: [CommissarMa/Context-Aware_Crowd_Counting-pytorch] 求问网盘上的模型是 Part_A的吗? (#17)



可以分享一下UCF-QNRF和UCF-50的pretrained model吗？非常感谢！
